server:
  port: 8080

spring:
  application:
    name: back_end_for_BOOKING

  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update # Options: update, create, drop, create-drop, validate, none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  access:
    secret-key: "12A5B3F6BF415258810FF3323F48893BC10DF7AFD938E07AA275F7884EC2E556" # Digit Hex Code in 64 bytes = 512 bits => HS512
    ttl-min: 43210 # (= 30 days) # 90

  refresh:
    secret-key: "5We890EcRZGHSK8eUoKHvk70q9OK+cgX62R8du+HmXfFDneHk7isAZF50LAx/srJKgZ8IaZCYY7ymhGQO7PLsg==" # Base 64 Url in 64 bytes = 512 bits => HS512
    ttl-days: 9
